service: nestjs-empowermentlabs

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - node_modules/**
    - .serverless/**
    - .env
  include:
    - dist/**

