service: nestjs-empowermentlabs

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
      Resource: 
        - 'arn:aws:dynamodb:us-east-2:446195074667:table/test*'

functions:
  app:
    handler: src/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline
  - serverless-bundle

package:
  individually: true

custom:
  bundle:
    sourcemaps: false
    copyFiles:
      - from: 'src/views'
        to: '/src/views'
