service: nestjs-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  app:
    handler: dist/main.handler
    events:
      - http: 'ANY {proxy+}'
      - http: 'ANY /'
