service: nestjs-empowermentlabs

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
      Resource: 
        - 'arn:aws:dynamodb:us-east-2:446195074667:table/test*'

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - .serverless/**
    - .env
  include:
    - node_modules/**
    - dist/**
