service: nestjs-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  app:
    handler: dist/main.handler
    events:
      - http: 
          path: /{proxy+}
          method: any
      - http: 
          path: /
          method: any

