name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Chequeo de Código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalación de dependencias
      run: npm ci

    - name: Instalar Serverless
      run: npm install -g serverless

    - name: Configurar AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configurar Variables de Entorno
      run: |
        echo _AWS_REGION=${{ secrets.AWS_REGION }} >> .env
        echo _AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo _AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env

    - name: Construir la aplicación
      run: npm run build

    - name: Desplegar con Serverless
      run: serverless deploy
